### ISSUE TITLE
Can not find gem

### ISSUE THREAD

**Issue by mitchenkod** [kristianmandrup/ember-beercan#2]
Something wrong with the gem ...
I type

```
$ gem install ember-beercan 
```

and get an error 

```
ERROR:  Could not find a valid gem 'ember-beercan' (>= 0) in any repository
```

**Comment by kristianmandrup** [comment]
Yes, it needs some major rework and debugging/testing. 
You are welcome to give it a try ;)
At the time I wrote ember beercan, it was my first attempt at writing Node javascript... 

I recommend you instead have a go with: https://github.com/kristianmandrup/permit-authorize
Using all the lessons learned from my various auhtorization libs...
Then you can wrap it in a gem for Rails if you like. Personally I would opt NOT to use the Rails asset pipeline and go with a pure Node based asset pipeline approach (a.la `gulp`, `webpack` or similar)

**Comment by mitchenkod** [comment]
Thank you for answer, but I decided, that for my needs would be better solution, just to create custom helper "can" in ember. It is nice idea, to make such gem, but I have no time time for contributing it... So, thank you again and good luck!
